import type { Metadata } from "next";
import "@/app/globals.css";
import Image from "next/image";
import Header from "@/app/components/header/header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <>
      <Header/>
        <div className="relative w-full  z-100">
          {children}
        </div>
      </>
  );
}
