import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import { AuthProvider } from "@/providers/auth";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <AuthProvider>
        <div className="relative w-full h-full z-100">
          {children}
        </div>
        <div className="fixed inset-0 -z-10">
            <Image
              src="/background.jpg"
              alt="BeachScore"
              fill
              priority
              sizes="100vw"
              quality={100}
              className="absolute inset-0 object-cover opacity-10 z-10"
            />
        <div className="absolute w-full h-full inset-0 bg-stone-900 z-0"></div>
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
